packages=(
	"zsh"
	"zsh-autocomplete-git"
	"zsh-autosuggestions"
	"zsh-syntax-highlighting"
	"starship"
	"exa"
	"bat"
	"ripgrep"
	"inter-font"
	"ttf-jetbrains-mono-nerd"
	"ttf-apple-emoji"
	"hyprland"
	"xdg-desktop-portal-hyprland-git"
	"hyprpaper-git"
	"waybar-hyprland"
	"rofi-lbonn-wayland"
	"mako"
	"cliphist"
	"grimblast-git"
	"pipewire-pulse"
	"playerctl"
	"udiskie"
	"kitty"
	"firefox"
	"webcord"
	"spotify"
	"spicetify-cli"
	"visual-studio-code-bin"
	"gnome-keyring"
)

for package in "${packages[@]}"; do
	paru -S --noconfirm "$package"
done
