packages=(
	"stow"
	"zsh"
	"zsh-autocomplete"
	"zsh-autosuggestions"
	"zsh-syntax-highlighting"
	"zsh-completions"
	"starship"
	"eza"
	"bat"
	"ripgrep"
	"ttf-jetbrains-mono-nerd"
	"ttf-apple-emoji"
	"xdg-user-dirs-gtk"
	"pipewire-pulse"
	"adw-gtk3"
	"firefox"
	"discord"
	"git-credential-manager-core-bin"
	"visual-studio-code-bin"
	"gnome-keyring"
)

exec paru -S "${packages[@]}"
