format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$cmd_duration\
$line_break\
$character"""

add_newline = false

[directory]
truncation_length = 6
truncation_symbol = '…/'
read_only = '󰍁 '
format = '[$read_only$path]($style) '

[git_branch]
symbol = "󰘬 "
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
style = 'bold purple'
tag_symbol = "󰓼 "

[git_state]
style = 'bold purple'

[git_status]
style = 'bold purple'
format = '[$all_status$ahead_behind]($style) '

[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '

[cmd_duration]
format = '[󰔛 $duration]($style) '
