add_newline = false

[aws]
format = '[󰸏 ($profile )(\($region\) )(\[$duration\] )]($style)'

[azure]
format = '[ ($subscription)]($style) '

[c]
format = '[ ($version(-$name) )]($style)'

[cmd_duration]
format = '[󰔛 $duration]($style) '

[crystal]
format = '[ ($version )]($style)'

[dart]
format = '[ ($version )]($style)'

[directory]
truncation_length = 6
truncation_symbol = '…/'
read_only = '󰍁 '
format = '[$read_only$path]($style) '

[docker_context]
format = '[󰡨 $context]($style) '

[dotnet]
format = '[󰪮 ($version )($tfm )]($style)'

[elixir]
format = '[ ($version \(OTP $otp_version\) )]($style)'

[elm]
format = '[ ($version )]($style)'

[erlang]
format = '[ ($version )]($style)'

[gcloud]
format = '[󱇶 $account(@$domain)(\($region\))]($style) '

[git_branch]
format = '[󰘬 $branch(:$remote_branch)]($style) '

[git_commit]
style = 'bold purple'
tag_symbol = "󰓼 "

[git_state]
style = 'bold purple'

[git_status]
style = 'bold purple'

[golang]
format = '[󰟓 ($version )]($style)'

[haskell]
format = '[ ($version )]($style)'

[haxe]
format = "[ ($version )]($style)"

[java]
format = '[󰬷 (${version} )]($style)'

[julia]
format = '[ ($version )]($style)'

[kotlin]
format = '[ ($version )]($style)'

[kubernetes]
format = '[󱃾 $context( \($namespace\))]($style) in '

[line_break]
disabled = true

[lua]
format = '[ ($version )]($style)'

[nim]
format = '[ ($version )]($style)'

[nodejs]
format = '[󰎙 ($version )]($style)'

[ocaml]
format = '[ ($version )(\($switch_indicator$switch_name\) )]($style)'

[package]
format = '[󰏗 $version]($style) '

[perl]
format = '[ ($version )]($style)'

[php]
format = '[󰌟 ($version )]($style)'

[purescript]
format = '[ ($version )]($style)'

[python]
format = '[ ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rlang]
format = '[ ($version )]($style)'

[ruby]
format = '[󰴭 ($version )]($style)'

[rust]
format = '[󱘗 ($version )]($style)'

[scala]
format = '[ (${version} )]($style)'

[swift]
format = '[ ($version )]($style)'

[terraform]
format = '[ $workspace]($style) '

[zig]
format = '[ ($version )]($style)'
